"""Inject Cell 11 (a–d) and Cell 12 into full_training_run.ipynb."""
import json
from pathlib import Path

NB_PATH = Path(__file__).parent / "full_training_run.ipynb"


def code_cell(source_lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": source_lines,
    }


def md_cell(source_lines):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source_lines,
    }


# ── Cell 11 header ───────────────────────────────────────────────────────────
md_11_header = md_cell([
    "## Cell 11 — Test-Set Evaluation of Shootout Checkpoints (dev-trained models)\n",
    "\n",
    "> **Note: this is the second time the test set is used.**\n",
    "> The first was the train+dev→test final-run evaluation (Final Cells A–E).\n",
    "> This second use evaluates the dev-trained shootout checkpoints on test for direct\n",
    "> dev-vs-test comparison, per supervisor request.\n",
    "> **Test set was not used to tune any hyperparameter.**\n",
    "\n",
    "Loads the four original shootout checkpoints (trained on `train.json` only) and\n",
    "evaluates each on the held-out `test.json`. No retraining is performed.\n",
    "\n",
    "| Sub-cell | Model | Stage | Checkpoint |\n",
    "|----------|-------|-------|------------|\n",
    "| 11a | BERT-base | Stage 1 | `bert_stage1/checkpoint-138/` |\n",
    "| 11b | BERT-base | Stage 2 | `bert_stage2/best_model.pt` |\n",
    "| 11c | RoBERTa-base | Stage 1 | `roberta_stage1/checkpoint-138/` |\n",
    "| 11d | RoBERTa-base | Stage 2 | `roberta_stage2/best_model.pt` |\n",
    "\n",
    "Outputs are saved locally and backed up to Drive.",
])

# ── Cell 11a markdown ────────────────────────────────────────────────────────
md_11a = md_cell([
    "### Cell 11a — BERT Stage 1 on Test\n",
    "\n",
    "Loads `bert_stage1/checkpoint-138/` (dev-trained shootout checkpoint) and evaluates\n",
    "on `test.json`. Saves `metrics.json` and `confusion_matrix.png` to\n",
    "`outputs/bert_stage1_test_eval/`. Also backs up to Drive.",
])

# ── Cell 11a code ────────────────────────────────────────────────────────────
code_11a = code_cell([
    "import json\n",
    "import os\n",
    "import shutil\n",
    "import sys\n",
    "\n",
    "import numpy as np\n",
    "import torch\n",
    "from torch.utils.data import DataLoader\n",
    "from transformers import AutoTokenizer, DataCollatorWithPadding\n",
    "from sklearn.metrics import precision_score, recall_score\n",
    "\n",
    "os.environ[\"HF_HOME\"] = \"/content/hf_cache\"\n",
    "sys.path.insert(0, \"/content/Bachelor-Thesis-IK\")\n",
    "\n",
    "from src.data import load_split\n",
    "from src.evaluate import compute_metrics_dict\n",
    "from src.model import build_model\n",
    "\n",
    "DRIVE_OUTPUT_DIR = \"/content/drive/MyDrive/CLT_Thesis/outputs\"\n",
    "CKPT_LOCAL = \"outputs/bert_stage1/checkpoint-138\"\n",
    "CKPT_DRIVE = f\"{DRIVE_OUTPUT_DIR}/bert_stage1/checkpoint-138\"\n",
    "OUT_LOCAL  = \"outputs/bert_stage1_test_eval\"\n",
    "OUT_DRIVE  = f\"{DRIVE_OUTPUT_DIR}/bert_stage1_test_eval\"\n",
    "TEST_PATH  = \"data/processed/test.json\"\n",
    "MAX_LENGTH = 128\n",
    "\n",
    "# Resolve checkpoint — prefer local, fall back to Drive\n",
    "ckpt_path = CKPT_LOCAL if os.path.isdir(CKPT_LOCAL) else CKPT_DRIVE\n",
    "if not os.path.isdir(ckpt_path):\n",
    "    raise FileNotFoundError(\n",
    "        f\"BERT Stage 1 checkpoint not found at {CKPT_LOCAL} or {CKPT_DRIVE}.\\n\"\n",
    "        \"Run Cell 5 first, or ensure the checkpoint is on Drive.\"\n",
    "    )\n",
    "print(f\"Loading checkpoint: {ckpt_path}\")\n",
    "\n",
    "os.makedirs(OUT_LOCAL, exist_ok=True)\n",
    "\n",
    "device    = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "tokenizer = AutoTokenizer.from_pretrained(ckpt_path)\n",
    "model     = build_model(ckpt_path)\n",
    "model.to(device).eval()\n",
    "\n",
    "def tokenize(batch):\n",
    "    return tokenizer(batch[\"text\"], truncation=True, max_length=MAX_LENGTH, padding=False)\n",
    "\n",
    "test_ds = load_split(TEST_PATH).map(tokenize, batched=True)\n",
    "test_ds = test_ds.remove_columns([\"text\"])\n",
    "test_ds.set_format(\"torch\")\n",
    "print(f\"Test set: {len(test_ds)} sentences\")\n",
    "\n",
    "collator = DataCollatorWithPadding(tokenizer)\n",
    "loader   = DataLoader(test_ds, batch_size=32, shuffle=False, collate_fn=collator)\n",
    "\n",
    "all_preds, all_gold = [], []\n",
    "with torch.no_grad():\n",
    "    for batch in loader:\n",
    "        logits = model(\n",
    "            input_ids=batch[\"input_ids\"].to(device),\n",
    "            attention_mask=batch[\"attention_mask\"].to(device),\n",
    "        ).logits\n",
    "        all_preds.extend(torch.argmax(logits, dim=-1).cpu().tolist())\n",
    "        all_gold.extend(batch[\"labels\"].tolist())\n",
    "\n",
    "# Core metrics via evaluate.py\n",
    "core = compute_metrics_dict(all_preds, all_gold)\n",
    "\n",
    "# Precision and recall per class (not emitted by evaluate.py)\n",
    "preds_arr = np.array(all_preds)\n",
    "gold_arr  = np.array(all_gold)\n",
    "per_class_precision = precision_score(\n",
    "    gold_arr, preds_arr, average=None, labels=[0, 1], zero_division=0\n",
    ").tolist()\n",
    "per_class_recall = recall_score(\n",
    "    gold_arr, preds_arr, average=None, labels=[0, 1], zero_division=0\n",
    ").tolist()\n",
    "\n",
    "metrics_out = {\n",
    "    \"macro_f1\":            core[\"macro_f1\"],\n",
    "    \"accuracy\":            core[\"accuracy\"],\n",
    "    \"per_class_precision\": per_class_precision,\n",
    "    \"per_class_recall\":    per_class_recall,\n",
    "    \"per_class_f1\":        core[\"per_class_f1\"],\n",
    "    \"confusion_matrix\":    core[\"confusion_matrix\"].tolist(),\n",
    "    \"krippendorff_alpha\":  core[\"krippendorff_alpha\"],\n",
    "}\n",
    "\n",
    "with open(f\"{OUT_LOCAL}/metrics.json\", \"w\") as f:\n",
    "    json.dump(metrics_out, f, indent=2)\n",
    "with open(f\"{OUT_LOCAL}/test_predictions.json\", \"w\") as f:\n",
    "    json.dump({\"predictions\": all_preds, \"gold\": all_gold}, f)\n",
    "\n",
    "# Confusion matrix PNG (winning model)\n",
    "try:\n",
    "    import matplotlib; matplotlib.use(\"Agg\")\n",
    "    import matplotlib.pyplot as plt\n",
    "    from sklearn.metrics import ConfusionMatrixDisplay\n",
    "    disp = ConfusionMatrixDisplay(\n",
    "        confusion_matrix=core[\"confusion_matrix\"],\n",
    "        display_labels=[\"not salient\", \"salient\"],\n",
    "    )\n",
    "    disp.plot(colorbar=False)\n",
    "    plt.title(\"Test confusion matrix — BERT Stage 1 (dev-trained)\")\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(f\"{OUT_LOCAL}/confusion_matrix.png\", dpi=150)\n",
    "    plt.close()\n",
    "    print(\"Confusion matrix PNG saved.\")\n",
    "except ImportError:\n",
    "    print(\"matplotlib not installed — skipping confusion matrix PNG\")\n",
    "\n",
    "# Back up to Drive\n",
    "if os.path.isdir(OUT_DRIVE):\n",
    "    shutil.rmtree(OUT_DRIVE)\n",
    "shutil.copytree(OUT_LOCAL, OUT_DRIVE)\n",
    "\n",
    "print(\"\\n\" + \"=\" * 60)\n",
    "print(\"BERT Stage 1 — TEST evaluation (dev-trained checkpoint)\")\n",
    "print(\"-\" * 60)\n",
    "print(f\"  Macro-F1 : {metrics_out['macro_f1']:.4f}\")\n",
    "print(f\"  Accuracy : {metrics_out['accuracy']:.4f}\")\n",
    "print(f\"  Kripp. α : {metrics_out['krippendorff_alpha']:.4f}\")\n",
    "print(f\"  Precision: not_salient={per_class_precision[0]:.4f}  salient={per_class_precision[1]:.4f}\")\n",
    "print(f\"  Recall   : not_salient={per_class_recall[0]:.4f}  salient={per_class_recall[1]:.4f}\")\n",
    "print(f\"  F1       : not_salient={core['per_class_f1'][0]:.4f}  salient={core['per_class_f1'][1]:.4f}\")\n",
    "print(\"  Confusion matrix (rows=gold, cols=pred):\")\n",
    "for row in metrics_out[\"confusion_matrix\"]:\n",
    "    print(f\"    {row}\")\n",
    "print(\"=\" * 60)\n",
    "print(f\"Outputs: {OUT_LOCAL}/  |  Drive: {OUT_DRIVE}/\")\n",
])

# ── Cell 11b markdown ────────────────────────────────────────────────────────
md_11b = md_cell([
    "### Cell 11b — BERT Stage 2 on Test\n",
    "\n",
    "Loads `bert_stage2/best_model.pt` and evaluates on the salient sentences of `test.json`.\n",
    "Saves `metrics.json` and one confusion matrix PNG per dimension\n",
    "(labelled `[\"N/A\", \"Near\", \"Far\"]`) to `outputs/bert_stage2_test_eval/`.",
])

# ── Cell 11b code ────────────────────────────────────────────────────────────
code_11b = code_cell([
    "import json\n",
    "import os\n",
    "import shutil\n",
    "import sys\n",
    "\n",
    "import numpy as np\n",
    "import torch\n",
    "from torch.utils.data import DataLoader\n",
    "from transformers import AutoTokenizer, DataCollatorWithPadding\n",
    "from sklearn.metrics import precision_score, recall_score\n",
    "\n",
    "os.environ[\"HF_HOME\"] = \"/content/hf_cache\"\n",
    "sys.path.insert(0, \"/content/Bachelor-Thesis-IK\")\n",
    "\n",
    "from src.data import DIMS, INV_LABEL_MAP, load_split_stage2\n",
    "from src.evaluate import evaluate_stage2\n",
    "from src.model import CLTStage2Model\n",
    "\n",
    "DRIVE_OUTPUT_DIR = \"/content/drive/MyDrive/CLT_Thesis/outputs\"\n",
    "CKPT_LOCAL = \"outputs/bert_stage2/best_model.pt\"\n",
    "CKPT_DRIVE = f\"{DRIVE_OUTPUT_DIR}/bert_stage2/best_model.pt\"\n",
    "CFG_LOCAL  = \"outputs/bert_stage2/config.yaml\"\n",
    "CFG_DRIVE  = f\"{DRIVE_OUTPUT_DIR}/bert_stage2/config.yaml\"\n",
    "OUT_LOCAL  = \"outputs/bert_stage2_test_eval\"\n",
    "OUT_DRIVE  = f\"{DRIVE_OUTPUT_DIR}/bert_stage2_test_eval\"\n",
    "TEST_PATH  = \"data/processed/test.json\"\n",
    "MAX_LENGTH = 128\n",
    "MODEL_NAME = \"bert-base-uncased\"\n",
    "\n",
    "# Resolve checkpoint\n",
    "ckpt_path = CKPT_LOCAL if os.path.exists(CKPT_LOCAL) else CKPT_DRIVE\n",
    "if not os.path.exists(ckpt_path):\n",
    "    raise FileNotFoundError(\n",
    "        f\"BERT Stage 2 checkpoint not found at {CKPT_LOCAL} or {CKPT_DRIVE}.\\n\"\n",
    "        \"Run Cell 6 first.\"\n",
    "    )\n",
    "print(f\"Loading checkpoint: {ckpt_path}\")\n",
    "\n",
    "# Resolve model_name from saved config if available\n",
    "cfg_path = CFG_LOCAL if os.path.exists(CFG_LOCAL) else (\n",
    "    CFG_DRIVE if os.path.exists(CFG_DRIVE) else None\n",
    ")\n",
    "if cfg_path:\n",
    "    import yaml\n",
    "    with open(cfg_path) as _f:\n",
    "        _cfg = yaml.safe_load(_f)\n",
    "    MODEL_NAME = _cfg.get(\"model_name\", MODEL_NAME)\n",
    "print(f\"Encoder base: {MODEL_NAME}\")\n",
    "\n",
    "os.makedirs(OUT_LOCAL, exist_ok=True)\n",
    "\n",
    "device    = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)\n",
    "model     = CLTStage2Model(MODEL_NAME).to(device)\n",
    "model.load_state_dict(torch.load(ckpt_path, map_location=device))\n",
    "model.eval()\n",
    "\n",
    "def tokenize_s2(batch):\n",
    "    return tokenizer(batch[\"text\"], truncation=True, max_length=MAX_LENGTH, padding=False)\n",
    "\n",
    "test_ds       = load_split_stage2(TEST_PATH).map(tokenize_s2, batched=True)\n",
    "test_ds_torch = test_ds.remove_columns([\"text\"])\n",
    "test_ds_torch.set_format(\"torch\")\n",
    "print(f\"Salient test sentences: {len(test_ds_torch)}\")\n",
    "\n",
    "collator = DataCollatorWithPadding(tokenizer)\n",
    "loader   = DataLoader(test_ds_torch, batch_size=32, shuffle=False, collate_fn=collator)\n",
    "\n",
    "all_preds = {d: [] for d in DIMS}\n",
    "all_gold  = {d: [] for d in DIMS}\n",
    "with torch.no_grad():\n",
    "    for batch in loader:\n",
    "        logits_dict = model(\n",
    "            input_ids=batch[\"input_ids\"].to(device),\n",
    "            attention_mask=batch[\"attention_mask\"].to(device),\n",
    "        )\n",
    "        for dim in DIMS:\n",
    "            pred_idx = torch.argmax(logits_dict[dim], dim=-1).cpu().tolist()\n",
    "            gold_idx = batch[dim].tolist()\n",
    "            all_preds[dim].extend(INV_LABEL_MAP[p] for p in pred_idx)\n",
    "            all_gold[dim].extend(INV_LABEL_MAP[g] for g in gold_idx)\n",
    "\n",
    "core = evaluate_stage2(all_preds, all_gold)\n",
    "\n",
    "# Build serialisable metrics dict with per-class precision/recall added\n",
    "metrics_out = {\"mean_macro_f1\": core[\"mean_macro_f1\"]}\n",
    "for dim in DIMS:\n",
    "    dm        = core[dim]\n",
    "    preds_arr = np.array(all_preds[dim])\n",
    "    gold_arr  = np.array(all_gold[dim])\n",
    "    per_class_precision = precision_score(\n",
    "        gold_arr, preds_arr, average=None, labels=[-1, 0, 1], zero_division=0\n",
    "    ).tolist()\n",
    "    per_class_recall = recall_score(\n",
    "        gold_arr, preds_arr, average=None, labels=[-1, 0, 1], zero_division=0\n",
    "    ).tolist()\n",
    "    metrics_out[dim] = {\n",
    "        \"macro_f1\":            dm[\"macro_f1\"],\n",
    "        \"per_class_precision\": per_class_precision,\n",
    "        \"per_class_recall\":    per_class_recall,\n",
    "        \"per_class_f1\":        dm[\"per_class_f1\"],\n",
    "        \"confusion_matrix\":    dm[\"confusion_matrix\"].tolist(),\n",
    "        \"krippendorff_alpha\":  dm[\"krippendorff_alpha\"],\n",
    "        \"collapsed\":           dm[\"collapsed\"],\n",
    "    }\n",
    "\n",
    "with open(f\"{OUT_LOCAL}/metrics.json\", \"w\") as f:\n",
    "    json.dump(metrics_out, f, indent=2)\n",
    "with open(f\"{OUT_LOCAL}/test_predictions.json\", \"w\") as f:\n",
    "    json.dump({\"predictions\": all_preds, \"gold\": all_gold}, f, indent=2)\n",
    "\n",
    "# Confusion matrix PNGs — one per dimension\n",
    "try:\n",
    "    import matplotlib; matplotlib.use(\"Agg\")\n",
    "    import matplotlib.pyplot as plt\n",
    "    from sklearn.metrics import ConfusionMatrixDisplay\n",
    "    for dim in DIMS:\n",
    "        cm   = core[dim][\"confusion_matrix\"]\n",
    "        disp = ConfusionMatrixDisplay(\n",
    "            confusion_matrix=cm, display_labels=[\"N/A\", \"Near\", \"Far\"]\n",
    "        )\n",
    "        disp.plot(colorbar=False)\n",
    "        plt.title(f\"Test confusion matrix — BERT Stage 2 {dim} (dev-trained)\")\n",
    "        plt.tight_layout()\n",
    "        plt.savefig(f\"{OUT_LOCAL}/confusion_matrix_{dim}.png\", dpi=150)\n",
    "        plt.close()\n",
    "    print(\"Confusion matrix PNGs saved.\")\n",
    "except ImportError:\n",
    "    print(\"matplotlib not installed — skipping confusion matrix PNGs\")\n",
    "\n",
    "# Back up to Drive\n",
    "if os.path.isdir(OUT_DRIVE):\n",
    "    shutil.rmtree(OUT_DRIVE)\n",
    "shutil.copytree(OUT_LOCAL, OUT_DRIVE)\n",
    "\n",
    "print(\"\\n\" + \"=\" * 60)\n",
    "print(\"BERT Stage 2 — TEST evaluation (dev-trained checkpoint)\")\n",
    "print(\"-\" * 60)\n",
    "print(f\"  Mean macro-F1 : {core['mean_macro_f1']:.4f}\")\n",
    "for dim in DIMS:\n",
    "    dm   = metrics_out[dim]\n",
    "    note = \"  [COLLAPSE]\" if dm[\"collapsed\"] else \"\"\n",
    "    print(f\"  {dim:<14}: macro-F1={dm['macro_f1']:.4f}  α={dm['krippendorff_alpha']:.4f}{note}\")\n",
    "print(\"=\" * 60)\n",
    "print(f\"Outputs: {OUT_LOCAL}/  |  Drive: {OUT_DRIVE}/\")\n",
])

# ── Cell 11c markdown ────────────────────────────────────────────────────────
md_11c = md_cell([
    "### Cell 11c — RoBERTa Stage 1 on Test\n",
    "\n",
    "Loads `roberta_stage1/checkpoint-138/` (dev-trained shootout checkpoint) and evaluates\n",
    "on `test.json`. Saves `metrics.json` and `confusion_matrix.png` to\n",
    "`outputs/roberta_stage1_test_eval/`.",
])

# ── Cell 11c code ────────────────────────────────────────────────────────────
code_11c = code_cell([
    "import json\n",
    "import os\n",
    "import shutil\n",
    "import sys\n",
    "\n",
    "import numpy as np\n",
    "import torch\n",
    "from torch.utils.data import DataLoader\n",
    "from transformers import AutoTokenizer, DataCollatorWithPadding\n",
    "from sklearn.metrics import precision_score, recall_score\n",
    "\n",
    "os.environ[\"HF_HOME\"] = \"/content/hf_cache\"\n",
    "sys.path.insert(0, \"/content/Bachelor-Thesis-IK\")\n",
    "\n",
    "from src.data import load_split\n",
    "from src.evaluate import compute_metrics_dict\n",
    "from src.model import build_model\n",
    "\n",
    "DRIVE_OUTPUT_DIR = \"/content/drive/MyDrive/CLT_Thesis/outputs\"\n",
    "CKPT_LOCAL = \"outputs/roberta_stage1/checkpoint-138\"\n",
    "CKPT_DRIVE = f\"{DRIVE_OUTPUT_DIR}/roberta_stage1/checkpoint-138\"\n",
    "OUT_LOCAL  = \"outputs/roberta_stage1_test_eval\"\n",
    "OUT_DRIVE  = f\"{DRIVE_OUTPUT_DIR}/roberta_stage1_test_eval\"\n",
    "TEST_PATH  = \"data/processed/test.json\"\n",
    "MAX_LENGTH = 128\n",
    "\n",
    "# Resolve checkpoint — prefer local, fall back to Drive\n",
    "ckpt_path = CKPT_LOCAL if os.path.isdir(CKPT_LOCAL) else CKPT_DRIVE\n",
    "if not os.path.isdir(ckpt_path):\n",
    "    raise FileNotFoundError(\n",
    "        f\"RoBERTa Stage 1 checkpoint not found at {CKPT_LOCAL} or {CKPT_DRIVE}.\\n\"\n",
    "        \"Run Cell 7 first, or ensure the checkpoint is on Drive.\"\n",
    "    )\n",
    "print(f\"Loading checkpoint: {ckpt_path}\")\n",
    "\n",
    "os.makedirs(OUT_LOCAL, exist_ok=True)\n",
    "\n",
    "device    = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "tokenizer = AutoTokenizer.from_pretrained(ckpt_path)\n",
    "model     = build_model(ckpt_path)\n",
    "model.to(device).eval()\n",
    "\n",
    "def tokenize(batch):\n",
    "    return tokenizer(batch[\"text\"], truncation=True, max_length=MAX_LENGTH, padding=False)\n",
    "\n",
    "test_ds = load_split(TEST_PATH).map(tokenize, batched=True)\n",
    "test_ds = test_ds.remove_columns([\"text\"])\n",
    "test_ds.set_format(\"torch\")\n",
    "print(f\"Test set: {len(test_ds)} sentences\")\n",
    "\n",
    "collator = DataCollatorWithPadding(tokenizer)\n",
    "loader   = DataLoader(test_ds, batch_size=32, shuffle=False, collate_fn=collator)\n",
    "\n",
    "all_preds, all_gold = [], []\n",
    "with torch.no_grad():\n",
    "    for batch in loader:\n",
    "        logits = model(\n",
    "            input_ids=batch[\"input_ids\"].to(device),\n",
    "            attention_mask=batch[\"attention_mask\"].to(device),\n",
    "        ).logits\n",
    "        all_preds.extend(torch.argmax(logits, dim=-1).cpu().tolist())\n",
    "        all_gold.extend(batch[\"labels\"].tolist())\n",
    "\n",
    "# Core metrics via evaluate.py\n",
    "core = compute_metrics_dict(all_preds, all_gold)\n",
    "\n",
    "# Precision and recall per class (not emitted by evaluate.py)\n",
    "preds_arr = np.array(all_preds)\n",
    "gold_arr  = np.array(all_gold)\n",
    "per_class_precision = precision_score(\n",
    "    gold_arr, preds_arr, average=None, labels=[0, 1], zero_division=0\n",
    ").tolist()\n",
    "per_class_recall = recall_score(\n",
    "    gold_arr, preds_arr, average=None, labels=[0, 1], zero_division=0\n",
    ").tolist()\n",
    "\n",
    "metrics_out = {\n",
    "    \"macro_f1\":            core[\"macro_f1\"],\n",
    "    \"accuracy\":            core[\"accuracy\"],\n",
    "    \"per_class_precision\": per_class_precision,\n",
    "    \"per_class_recall\":    per_class_recall,\n",
    "    \"per_class_f1\":        core[\"per_class_f1\"],\n",
    "    \"confusion_matrix\":    core[\"confusion_matrix\"].tolist(),\n",
    "    \"krippendorff_alpha\":  core[\"krippendorff_alpha\"],\n",
    "}\n",
    "\n",
    "with open(f\"{OUT_LOCAL}/metrics.json\", \"w\") as f:\n",
    "    json.dump(metrics_out, f, indent=2)\n",
    "with open(f\"{OUT_LOCAL}/test_predictions.json\", \"w\") as f:\n",
    "    json.dump({\"predictions\": all_preds, \"gold\": all_gold}, f)\n",
    "\n",
    "# Confusion matrix PNG\n",
    "try:\n",
    "    import matplotlib; matplotlib.use(\"Agg\")\n",
    "    import matplotlib.pyplot as plt\n",
    "    from sklearn.metrics import ConfusionMatrixDisplay\n",
    "    disp = ConfusionMatrixDisplay(\n",
    "        confusion_matrix=core[\"confusion_matrix\"],\n",
    "        display_labels=[\"not salient\", \"salient\"],\n",
    "    )\n",
    "    disp.plot(colorbar=False)\n",
    "    plt.title(\"Test confusion matrix — RoBERTa Stage 1 (dev-trained)\")\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(f\"{OUT_LOCAL}/confusion_matrix.png\", dpi=150)\n",
    "    plt.close()\n",
    "    print(\"Confusion matrix PNG saved.\")\n",
    "except ImportError:\n",
    "    print(\"matplotlib not installed — skipping confusion matrix PNG\")\n",
    "\n",
    "# Back up to Drive\n",
    "if os.path.isdir(OUT_DRIVE):\n",
    "    shutil.rmtree(OUT_DRIVE)\n",
    "shutil.copytree(OUT_LOCAL, OUT_DRIVE)\n",
    "\n",
    "print(\"\\n\" + \"=\" * 60)\n",
    "print(\"RoBERTa Stage 1 — TEST evaluation (dev-trained checkpoint)\")\n",
    "print(\"-\" * 60)\n",
    "print(f\"  Macro-F1 : {metrics_out['macro_f1']:.4f}\")\n",
    "print(f\"  Accuracy : {metrics_out['accuracy']:.4f}\")\n",
    "print(f\"  Kripp. α : {metrics_out['krippendorff_alpha']:.4f}\")\n",
    "print(f\"  Precision: not_salient={per_class_precision[0]:.4f}  salient={per_class_precision[1]:.4f}\")\n",
    "print(f\"  Recall   : not_salient={per_class_recall[0]:.4f}  salient={per_class_recall[1]:.4f}\")\n",
    "print(f\"  F1       : not_salient={core['per_class_f1'][0]:.4f}  salient={core['per_class_f1'][1]:.4f}\")\n",
    "print(\"  Confusion matrix (rows=gold, cols=pred):\")\n",
    "for row in metrics_out[\"confusion_matrix\"]:\n",
    "    print(f\"    {row}\")\n",
    "print(\"=\" * 60)\n",
    "print(f\"Outputs: {OUT_LOCAL}/  |  Drive: {OUT_DRIVE}/\")\n",
])

# ── Cell 11d markdown ────────────────────────────────────────────────────────
md_11d = md_cell([
    "### Cell 11d — RoBERTa Stage 2 on Test\n",
    "\n",
    "Loads `roberta_stage2/best_model.pt` and evaluates on the salient sentences of `test.json`.\n",
    "Saves `metrics.json` and one confusion matrix PNG per dimension\n",
    "(labelled `[\"N/A\", \"Near\", \"Far\"]`) to `outputs/roberta_stage2_test_eval/`.",
])

# ── Cell 11d code ────────────────────────────────────────────────────────────
code_11d = code_cell([
    "import json\n",
    "import os\n",
    "import shutil\n",
    "import sys\n",
    "\n",
    "import numpy as np\n",
    "import torch\n",
    "from torch.utils.data import DataLoader\n",
    "from transformers import AutoTokenizer, DataCollatorWithPadding\n",
    "from sklearn.metrics import precision_score, recall_score\n",
    "\n",
    "os.environ[\"HF_HOME\"] = \"/content/hf_cache\"\n",
    "sys.path.insert(0, \"/content/Bachelor-Thesis-IK\")\n",
    "\n",
    "from src.data import DIMS, INV_LABEL_MAP, load_split_stage2\n",
    "from src.evaluate import evaluate_stage2\n",
    "from src.model import CLTStage2Model\n",
    "\n",
    "DRIVE_OUTPUT_DIR = \"/content/drive/MyDrive/CLT_Thesis/outputs\"\n",
    "CKPT_LOCAL = \"outputs/roberta_stage2/best_model.pt\"\n",
    "CKPT_DRIVE = f\"{DRIVE_OUTPUT_DIR}/roberta_stage2/best_model.pt\"\n",
    "CFG_LOCAL  = \"outputs/roberta_stage2/config.yaml\"\n",
    "CFG_DRIVE  = f\"{DRIVE_OUTPUT_DIR}/roberta_stage2/config.yaml\"\n",
    "OUT_LOCAL  = \"outputs/roberta_stage2_test_eval\"\n",
    "OUT_DRIVE  = f\"{DRIVE_OUTPUT_DIR}/roberta_stage2_test_eval\"\n",
    "TEST_PATH  = \"data/processed/test.json\"\n",
    "MAX_LENGTH = 128\n",
    "MODEL_NAME = \"roberta-base\"\n",
    "\n",
    "# Resolve checkpoint\n",
    "ckpt_path = CKPT_LOCAL if os.path.exists(CKPT_LOCAL) else CKPT_DRIVE\n",
    "if not os.path.exists(ckpt_path):\n",
    "    raise FileNotFoundError(\n",
    "        f\"RoBERTa Stage 2 checkpoint not found at {CKPT_LOCAL} or {CKPT_DRIVE}.\\n\"\n",
    "        \"Run Cell 8 first.\"\n",
    "    )\n",
    "print(f\"Loading checkpoint: {ckpt_path}\")\n",
    "\n",
    "# Resolve model_name from saved config if available\n",
    "cfg_path = CFG_LOCAL if os.path.exists(CFG_LOCAL) else (\n",
    "    CFG_DRIVE if os.path.exists(CFG_DRIVE) else None\n",
    ")\n",
    "if cfg_path:\n",
    "    import yaml\n",
    "    with open(cfg_path) as _f:\n",
    "        _cfg = yaml.safe_load(_f)\n",
    "    MODEL_NAME = _cfg.get(\"model_name\", MODEL_NAME)\n",
    "print(f\"Encoder base: {MODEL_NAME}\")\n",
    "\n",
    "os.makedirs(OUT_LOCAL, exist_ok=True)\n",
    "\n",
    "device    = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
    "tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)\n",
    "model     = CLTStage2Model(MODEL_NAME).to(device)\n",
    "model.load_state_dict(torch.load(ckpt_path, map_location=device))\n",
    "model.eval()\n",
    "\n",
    "def tokenize_s2(batch):\n",
    "    return tokenizer(batch[\"text\"], truncation=True, max_length=MAX_LENGTH, padding=False)\n",
    "\n",
    "test_ds       = load_split_stage2(TEST_PATH).map(tokenize_s2, batched=True)\n",
    "test_ds_torch = test_ds.remove_columns([\"text\"])\n",
    "test_ds_torch.set_format(\"torch\")\n",
    "print(f\"Salient test sentences: {len(test_ds_torch)}\")\n",
    "\n",
    "collator = DataCollatorWithPadding(tokenizer)\n",
    "loader   = DataLoader(test_ds_torch, batch_size=32, shuffle=False, collate_fn=collator)\n",
    "\n",
    "all_preds = {d: [] for d in DIMS}\n",
    "all_gold  = {d: [] for d in DIMS}\n",
    "with torch.no_grad():\n",
    "    for batch in loader:\n",
    "        logits_dict = model(\n",
    "            input_ids=batch[\"input_ids\"].to(device),\n",
    "            attention_mask=batch[\"attention_mask\"].to(device),\n",
    "        )\n",
    "        for dim in DIMS:\n",
    "            pred_idx = torch.argmax(logits_dict[dim], dim=-1).cpu().tolist()\n",
    "            gold_idx = batch[dim].tolist()\n",
    "            all_preds[dim].extend(INV_LABEL_MAP[p] for p in pred_idx)\n",
    "            all_gold[dim].extend(INV_LABEL_MAP[g] for g in gold_idx)\n",
    "\n",
    "core = evaluate_stage2(all_preds, all_gold)\n",
    "\n",
    "# Build serialisable metrics dict with per-class precision/recall added\n",
    "metrics_out = {\"mean_macro_f1\": core[\"mean_macro_f1\"]}\n",
    "for dim in DIMS:\n",
    "    dm        = core[dim]\n",
    "    preds_arr = np.array(all_preds[dim])\n",
    "    gold_arr  = np.array(all_gold[dim])\n",
    "    per_class_precision = precision_score(\n",
    "        gold_arr, preds_arr, average=None, labels=[-1, 0, 1], zero_division=0\n",
    "    ).tolist()\n",
    "    per_class_recall = recall_score(\n",
    "        gold_arr, preds_arr, average=None, labels=[-1, 0, 1], zero_division=0\n",
    "    ).tolist()\n",
    "    metrics_out[dim] = {\n",
    "        \"macro_f1\":            dm[\"macro_f1\"],\n",
    "        \"per_class_precision\": per_class_precision,\n",
    "        \"per_class_recall\":    per_class_recall,\n",
    "        \"per_class_f1\":        dm[\"per_class_f1\"],\n",
    "        \"confusion_matrix\":    dm[\"confusion_matrix\"].tolist(),\n",
    "        \"krippendorff_alpha\":  dm[\"krippendorff_alpha\"],\n",
    "        \"collapsed\":           dm[\"collapsed\"],\n",
    "    }\n",
    "\n",
    "with open(f\"{OUT_LOCAL}/metrics.json\", \"w\") as f:\n",
    "    json.dump(metrics_out, f, indent=2)\n",
    "with open(f\"{OUT_LOCAL}/test_predictions.json\", \"w\") as f:\n",
    "    json.dump({\"predictions\": all_preds, \"gold\": all_gold}, f, indent=2)\n",
    "\n",
    "# Confusion matrix PNGs — one per dimension\n",
    "try:\n",
    "    import matplotlib; matplotlib.use(\"Agg\")\n",
    "    import matplotlib.pyplot as plt\n",
    "    from sklearn.metrics import ConfusionMatrixDisplay\n",
    "    for dim in DIMS:\n",
    "        cm   = core[dim][\"confusion_matrix\"]\n",
    "        disp = ConfusionMatrixDisplay(\n",
    "            confusion_matrix=cm, display_labels=[\"N/A\", \"Near\", \"Far\"]\n",
    "        )\n",
    "        disp.plot(colorbar=False)\n",
    "        plt.title(f\"Test confusion matrix — RoBERTa Stage 2 {dim} (dev-trained)\")\n",
    "        plt.tight_layout()\n",
    "        plt.savefig(f\"{OUT_LOCAL}/confusion_matrix_{dim}.png\", dpi=150)\n",
    "        plt.close()\n",
    "    print(\"Confusion matrix PNGs saved.\")\n",
    "except ImportError:\n",
    "    print(\"matplotlib not installed — skipping confusion matrix PNGs\")\n",
    "\n",
    "# Back up to Drive\n",
    "if os.path.isdir(OUT_DRIVE):\n",
    "    shutil.rmtree(OUT_DRIVE)\n",
    "shutil.copytree(OUT_LOCAL, OUT_DRIVE)\n",
    "\n",
    "print(\"\\n\" + \"=\" * 60)\n",
    "print(\"RoBERTa Stage 2 — TEST evaluation (dev-trained checkpoint)\")\n",
    "print(\"-\" * 60)\n",
    "print(f\"  Mean macro-F1 : {core['mean_macro_f1']:.4f}\")\n",
    "for dim in DIMS:\n",
    "    dm   = metrics_out[dim]\n",
    "    note = \"  [COLLAPSE]\" if dm[\"collapsed\"] else \"\"\n",
    "    print(f\"  {dim:<14}: macro-F1={dm['macro_f1']:.4f}  α={dm['krippendorff_alpha']:.4f}{note}\")\n",
    "print(\"=\" * 60)\n",
    "print(f\"Outputs: {OUT_LOCAL}/  |  Drive: {OUT_DRIVE}/\")\n",
])

# ── Cell 12 markdown ─────────────────────────────────────────────────────────
md_12 = md_cell([
    "## Cell 12 — Combined Results Table\n",
    "\n",
    "Loads `metrics.json` from all eight runs (four dev-shootout + four test-eval) and prints:\n",
    "\n",
    "1. **Summary table** — Model | Stage | Dev macro-F1 | Test macro-F1 (Stage 2 per dimension).\n",
    "2. **Winning-model diagnostic** — BERT Stage 1 test: full precision / recall / F1 /\n",
    "   confusion matrix, labelled \"Winning model — full diagnostic on test set\".",
])

# ── Cell 12 code ─────────────────────────────────────────────────────────────
code_12 = code_cell([
    "import json\n",
    "import os\n",
    "\n",
    "DRIVE_BASE = \"/content/drive/MyDrive/CLT_Thesis/outputs\"\n",
    "DIMS = (\"temporal\", \"spatial\", \"social\", \"hypothetical\")\n",
    "\n",
    "\n",
    "def _load_json(local_path, drive_path=None):\n",
    "    if os.path.exists(local_path):\n",
    "        with open(local_path) as f:\n",
    "            return json.load(f)\n",
    "    if drive_path and os.path.exists(drive_path):\n",
    "        with open(drive_path) as f:\n",
    "            return json.load(f)\n",
    "    return None\n",
    "\n",
    "\n",
    "def load_s1(run_name):\n",
    "    return _load_json(\n",
    "        f\"outputs/{run_name}/metrics.json\",\n",
    "        f\"{DRIVE_BASE}/{run_name}/metrics.json\",\n",
    "    )\n",
    "\n",
    "\n",
    "def load_s2_best(run_name):\n",
    "    \"\"\"Test-eval runs write a single metrics.json; dev-shootout runs write epoch_metrics.json.\"\"\"\n",
    "    direct = _load_json(\n",
    "        f\"outputs/{run_name}/metrics.json\",\n",
    "        f\"{DRIVE_BASE}/{run_name}/metrics.json\",\n",
    "    )\n",
    "    if direct is not None and \"mean_macro_f1\" in direct:\n",
    "        return direct\n",
    "    epoch_data = _load_json(\n",
    "        f\"outputs/{run_name}/epoch_metrics.json\",\n",
    "        f\"{DRIVE_BASE}/{run_name}/epoch_metrics.json\",\n",
    "    )\n",
    "    if epoch_data is not None:\n",
    "        return max(epoch_data, key=lambda r: r[\"mean_macro_f1\"])\n",
    "    return None\n",
    "\n",
    "\n",
    "def fmt(val):\n",
    "    return f\"{val:.4f}\" if val is not None else \"  N/A  \"\n",
    "\n",
    "\n",
    "# Load all eight metric files\n",
    "bert_s1_dev   = load_s1(\"bert_stage1\")\n",
    "bert_s2_dev   = load_s2_best(\"bert_stage2\")\n",
    "rob_s1_dev    = load_s1(\"roberta_stage1\")\n",
    "rob_s2_dev    = load_s2_best(\"roberta_stage2\")\n",
    "bert_s1_test  = load_s1(\"bert_stage1_test_eval\")\n",
    "bert_s2_test  = load_s2_best(\"bert_stage2_test_eval\")\n",
    "rob_s1_test   = load_s1(\"roberta_stage1_test_eval\")\n",
    "rob_s2_test   = load_s2_best(\"roberta_stage2_test_eval\")\n",
    "\n",
    "for label, obj in [\n",
    "    (\"bert_stage1 (dev)\",         bert_s1_dev),\n",
    "    (\"bert_stage2 (dev)\",         bert_s2_dev),\n",
    "    (\"roberta_stage1 (dev)\",      rob_s1_dev),\n",
    "    (\"roberta_stage2 (dev)\",      rob_s2_dev),\n",
    "    (\"bert_stage1_test_eval\",     bert_s1_test),\n",
    "    (\"bert_stage2_test_eval\",     bert_s2_test),\n",
    "    (\"roberta_stage1_test_eval\",  rob_s1_test),\n",
    "    (\"roberta_stage2_test_eval\",  rob_s2_test),\n",
    "]:\n",
    "    if obj is None:\n",
    "        print(f\"WARNING: metrics not found for {label} — run the corresponding cell first.\")\n",
    "\n",
    "# ── Summary table ─────────────────────────────────────────────────────────────\n",
    "SEP = \"=\" * 75\n",
    "print()\n",
    "print(SEP)\n",
    "print(\"SHOOTOUT CHECKPOINTS — Dev vs Test macro-F1 (dev-trained models)\")\n",
    "print(SEP)\n",
    "HDR = f\"{'Model':<14}  {'Stage':<20}  {'Dev macro-F1':>12}  {'Test macro-F1':>13}\"\n",
    "print(HDR)\n",
    "print(\"-\" * len(HDR))\n",
    "\n",
    "\n",
    "def s1_row(model_label, dev_obj, test_obj):\n",
    "    dev_f1  = dev_obj[\"macro_f1\"]  if dev_obj  else None\n",
    "    test_f1 = test_obj[\"macro_f1\"] if test_obj else None\n",
    "    print(f\"{model_label:<14}  {'Stage 1 (salience)':<20}  {fmt(dev_f1):>12}  {fmt(test_f1):>13}\")\n",
    "\n",
    "\n",
    "def s2_rows(model_label, dev_obj, test_obj):\n",
    "    for dim in DIMS:\n",
    "        dev_f1   = dev_obj[dim][\"macro_f1\"]  if dev_obj  and dim in dev_obj  else None\n",
    "        test_f1  = test_obj[dim][\"macro_f1\"] if test_obj and dim in test_obj else None\n",
    "        dev_col  = dev_obj[dim].get(\"collapsed\", False)  if dev_obj  and dim in dev_obj  else False\n",
    "        test_col = test_obj[dim].get(\"collapsed\", False) if test_obj and dim in test_obj else False\n",
    "        dev_str  = fmt(dev_f1)  + (\" [C]\" if dev_col  else \"\")\n",
    "        test_str = fmt(test_f1) + (\" [C]\" if test_col else \"\")\n",
    "        print(f\"{model_label:<14}  {f'Stage 2 — {dim}':<20}  {dev_str:>12}  {test_str:>13}\")\n",
    "    dev_mean  = dev_obj[\"mean_macro_f1\"]  if dev_obj  else None\n",
    "    test_mean = test_obj[\"mean_macro_f1\"] if test_obj else None\n",
    "    print(f\"{model_label:<14}  {'Stage 2 — MEAN':<20}  {fmt(dev_mean):>12}  {fmt(test_mean):>13}\")\n",
    "\n",
    "\n",
    "s1_row(\"BERT-base\",     bert_s1_dev,  bert_s1_test)\n",
    "s2_rows(\"BERT-base\",    bert_s2_dev,  bert_s2_test)\n",
    "print(\"-\" * len(HDR))\n",
    "s1_row(\"RoBERTa-base\",  rob_s1_dev,   rob_s1_test)\n",
    "s2_rows(\"RoBERTa-base\", rob_s2_dev,   rob_s2_test)\n",
    "print(SEP)\n",
    "print(\"[C] = model collapsed to predicting a single class for that dimension.\")\n",
    "print()\n",
    "\n",
    "# ── Winning model full diagnostic ─────────────────────────────────────────────\n",
    "print(SEP)\n",
    "print(\"Winning model — full diagnostic on test set\")\n",
    "print(\"BERT-base Stage 1 (dev-trained shootout checkpoint, evaluated on test.json)\")\n",
    "print(SEP)\n",
    "if bert_s1_test is None:\n",
    "    print(\"  WARNING: bert_stage1_test_eval metrics not found — run Cell 11a first.\")\n",
    "else:\n",
    "    m = bert_s1_test\n",
    "    print(f\"  Macro-F1    : {m['macro_f1']:.4f}\")\n",
    "    print(f\"  Accuracy    : {m['accuracy']:.4f}\")\n",
    "    print(f\"  Kripp. α    : {m['krippendorff_alpha']:.4f}\")\n",
    "    print()\n",
    "    print(\"  Per-class metrics:\")\n",
    "    print(f\"  {'Class':<14}  {'Precision':>9}  {'Recall':>9}  {'F1':>9}\")\n",
    "    print(f\"  {'-'*14}  {'-'*9}  {'-'*9}  {'-'*9}\")\n",
    "    for i, lbl in enumerate([\"not_salient\", \"salient\"]):\n",
    "        p = m[\"per_class_precision\"][i]\n",
    "        r = m[\"per_class_recall\"][i]\n",
    "        f = m[\"per_class_f1\"][i]\n",
    "        print(f\"  {lbl:<14}  {p:>9.4f}  {r:>9.4f}  {f:>9.4f}\")\n",
    "    print()\n",
    "    print(\"  Confusion matrix (rows=gold, cols=pred):\")\n",
    "    print(f\"  {'':14}  {'pred: not_sal':>13}  {'pred: salient':>13}\")\n",
    "    for i, row_lbl in enumerate([\"gold: not_sal\", \"gold: salient\"]):\n",
    "        row = m[\"confusion_matrix\"][i]\n",
    "        print(f\"  {row_lbl:<14}  {row[0]:>13}  {row[1]:>13}\")\n",
    "print(SEP)\n",
])

# ── Splice new cells into the notebook ───────────────────────────────────────
with open(NB_PATH, encoding="utf-8") as f:
    nb = json.load(f)

new_cells = [
    md_11_header,
    md_11a, code_11a,
    md_11b, code_11b,
    md_11c, code_11c,
    md_11d, code_11d,
    md_12,  code_12,
]

# Insert at index 21 (between Cell 10 code cell and Final-model separator)
INSERT_POS = 21
nb["cells"] = nb["cells"][:INSERT_POS] + new_cells + nb["cells"][INSERT_POS:]

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Done. Notebook now has {len(nb['cells'])} cells.")
print(f"Inserted {len(new_cells)} cells at position {INSERT_POS}.")
